name: Publish Docker image
on:
  push:
    tags:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        with:
          fetch-depth: 1
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push docker image
        with:
          image: codecentric/plantuml-docker
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}